name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn start
